name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      
      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown
      
      - name: Prepare Deployment Directory
        run: |
          mkdir -p ./deploy/fonts
          cp ./target/wasm32-unknown-unknown/release/mini_spreadsheet.wasm ./deploy/
          cp index.html ./deploy/
          cp -r fonts/ ./deploy/fonts/
          # Add .htaccess file
          echo "AddType application/wasm .wasm" > ./deploy/.htaccess
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy